{
  try {
    exec("byte x = 2; x *= 128; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("byte x = 2; x *= -128; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = 2; x *= 65536; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("char x = 2; x *= -65536; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = 2; x *= 2147483647; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("int x = 2; x *= -2147483647; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = 2; x *= 9223372036854775807L; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
  try {
    exec("long x = 2; x *= -9223372036854775807L; return x;");
    fail("did not get expected exception");
  }
 catch (  ArithmeticException expected) {
  }
}
