{
  if (current.getTragicException() != null) {
    try {
      close();
    }
 catch (    AlreadyClosedException inner) {
    }
catch (    Exception inner) {
      assert(ex != inner.getCause());
      ex.addSuppressed(inner);
    }
  }
}
