{
  RuntimeException exception=new RuntimeException();
  Callable<?> afterCallable=mock(Callable.class);
  AbstractRunnable runnable=new AbstractRunnable(){
    @Override public void onFailure(    Throwable t){
      assertSame(exception,t);
    }
    @Override protected void doRun() throws Exception {
      throw exception;
    }
    @Override public void onAfter(){
      try {
        afterCallable.call();
      }
 catch (      Exception e) {
        fail("Unexpected for mock.");
      }
    }
  }
;
  runnable.run();
  verify(afterCallable).call();
}
