{
  try {
    doTest(script);
    fail("did not get expected exception");
  }
 catch (  ScriptException expected) {
    Throwable cause=expected.getCause();
    assertNotNull(cause);
    assertTrue("unexpected exception: " + cause,cause instanceof SecurityException);
  }
}
