{
  try {
    listener.onFailure(source,t);
  }
 catch (  Exception e) {
    logger.error("exception thrown by listener notifying of failure [{}] from [{}]",e,t,source);
  }
}
